/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const EntertainmentPost = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Principal,
  'likes' : IDL.Nat,
  'creationDate' : Time,
  'comments' : IDL.Vec(Comment),
  'mediaId' : IDL.Opt(IDL.Text),
});
export const FilterPreset = IDL.Record({
  'name' : IDL.Text,
  'settings' : IDL.Record({
    'contrast' : IDL.Float64,
    'brightness' : IDL.Float64,
    'saturation' : IDL.Float64,
  }),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Ratings = IDL.Record({
  'funFactor' : IDL.Float64,
  'creative' : IDL.Float64,
  'technical' : IDL.Float64,
  'overall' : IDL.Float64,
});
export const MediaMetadata = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Opt(IDL.Nat),
  'owner' : IDL.Principal,
  'blob' : ExternalBlob,
  'tags' : IDL.Vec(IDL.Text),
  'ratings' : Ratings,
  'likedBy' : IDL.Vec(IDL.Principal),
  'isFavorite' : IDL.Bool,
  'likes' : IDL.Nat,
  'filename' : IDL.Text,
  'creationDate' : Time,
  'comments' : IDL.Vec(Comment),
  'isVideo' : IDL.Bool,
  'arEffectsApplied' : IDL.Vec(IDL.Text),
  'filtersApplied' : IDL.Vec(IDL.Text),
});
export const Story = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'tags' : IDL.Vec(IDL.Text),
  'creationDate' : Time,
  'expirationDate' : Time,
  'viewers' : IDL.Vec(IDL.Principal),
  'mediaId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'stories' : IDL.Vec(IDL.Text),
  'posts' : IDL.Vec(IDL.Text),
  'profilePictureBlob' : IDL.Opt(ExternalBlob),
  'videos' : IDL.Vec(IDL.Text),
});
export const Window = IDL.Variant({
  'editing' : IDL.Null,
  'entertainment' : IDL.Null,
  'stories' : IDL.Null,
  'aiTools' : IDL.Null,
  'lucky' : IDL.Null,
  'enhance' : IDL.Null,
  'settings' : IDL.Null,
  'nearby20' : IDL.Null,
  'camera' : IDL.Null,
  'gallery' : IDL.Null,
});
export const NearbyPost = IDL.Record({
  'id' : IDL.Text,
  'originalId' : IDL.Text,
  'owner' : IDL.Principal,
  'metadata' : MediaMetadata,
  'location' : IDL.Text,
});
export const EnhancedSidebarState = IDL.Record({
  'isOpen' : IDL.Bool,
  'activeWindow' : Window,
  'position' : IDL.Text,
});
export const SideBarResponse = IDL.Variant({
  'error' : IDL.Text,
  'success' : EnhancedSidebarState,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCommentToMedia' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addFilterPreset' : IDL.Func(
      [
        IDL.Text,
        IDL.Record({
          'contrast' : IDL.Float64,
          'brightness' : IDL.Float64,
          'saturation' : IDL.Float64,
        }),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMedia' : IDL.Func([IDL.Text], [], []),
  'getAllEntertainmentPosts' : IDL.Func(
      [],
      [IDL.Vec(EntertainmentPost)],
      ['query'],
    ),
  'getAllEntertainmentPostsSorted' : IDL.Func(
      [],
      [IDL.Vec(EntertainmentPost)],
      ['query'],
    ),
  'getAllFilterPresets' : IDL.Func([], [IDL.Vec(FilterPreset)], ['query']),
  'getAllMediaMetadata' : IDL.Func([], [IDL.Vec(MediaMetadata)], ['query']),
  'getAllNonExpiredStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentWindow' : IDL.Func([], [Window], ['query']),
  'getEntertainmentPost' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(EntertainmentPost)],
      ['query'],
    ),
  'getMediaByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MediaMetadata)],
      ['query'],
    ),
  'getMediaByTag' : IDL.Func([IDL.Text], [IDL.Vec(MediaMetadata)], ['query']),
  'getMediaMetadata' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MediaMetadata)],
      ['query'],
    ),
  'getMostPopularMedia' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MediaMetadata)],
      ['query'],
    ),
  'getNearbyPosts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(NearbyPost)],
      ['query'],
    ),
  'getNearbyPostsWithinTimeRange' : IDL.Func(
      [IDL.Text, Time, Time],
      [IDL.Vec(NearbyPost)],
      ['query'],
    ),
  'getNonExpiredUserStories' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Story)],
      ['query'],
    ),
  'getPostsByAuthor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(EntertainmentPost)],
      ['query'],
    ),
  'getSidebarState' : IDL.Func([], [SideBarResponse], ['query']),
  'getStory' : IDL.Func([IDL.Text], [IDL.Opt(Story)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfilesByUsername' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getUserStories' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAREffect' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveEntertainmentPost' : IDL.Func([EntertainmentPost], [], []),
  'saveMedia' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        ExternalBlob,
        IDL.Principal,
        IDL.Bool,
        IDL.Opt(IDL.Nat),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'saveNearbyPost' : IDL.Func([NearbyPost], [], []),
  'saveUserStory' : IDL.Func([Story], [], []),
  'setFavoriteStatusForMedia' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setLikeStatusForMedia' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setSidebarPosition' : IDL.Func([IDL.Text], [], []),
  'switchWindow' : IDL.Func([Window], [], []),
  'toggleSidebar' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const EntertainmentPost = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Principal,
    'likes' : IDL.Nat,
    'creationDate' : Time,
    'comments' : IDL.Vec(Comment),
    'mediaId' : IDL.Opt(IDL.Text),
  });
  const FilterPreset = IDL.Record({
    'name' : IDL.Text,
    'settings' : IDL.Record({
      'contrast' : IDL.Float64,
      'brightness' : IDL.Float64,
      'saturation' : IDL.Float64,
    }),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Ratings = IDL.Record({
    'funFactor' : IDL.Float64,
    'creative' : IDL.Float64,
    'technical' : IDL.Float64,
    'overall' : IDL.Float64,
  });
  const MediaMetadata = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Opt(IDL.Nat),
    'owner' : IDL.Principal,
    'blob' : ExternalBlob,
    'tags' : IDL.Vec(IDL.Text),
    'ratings' : Ratings,
    'likedBy' : IDL.Vec(IDL.Principal),
    'isFavorite' : IDL.Bool,
    'likes' : IDL.Nat,
    'filename' : IDL.Text,
    'creationDate' : Time,
    'comments' : IDL.Vec(Comment),
    'isVideo' : IDL.Bool,
    'arEffectsApplied' : IDL.Vec(IDL.Text),
    'filtersApplied' : IDL.Vec(IDL.Text),
  });
  const Story = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'tags' : IDL.Vec(IDL.Text),
    'creationDate' : Time,
    'expirationDate' : Time,
    'viewers' : IDL.Vec(IDL.Principal),
    'mediaId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'stories' : IDL.Vec(IDL.Text),
    'posts' : IDL.Vec(IDL.Text),
    'profilePictureBlob' : IDL.Opt(ExternalBlob),
    'videos' : IDL.Vec(IDL.Text),
  });
  const Window = IDL.Variant({
    'editing' : IDL.Null,
    'entertainment' : IDL.Null,
    'stories' : IDL.Null,
    'aiTools' : IDL.Null,
    'lucky' : IDL.Null,
    'enhance' : IDL.Null,
    'settings' : IDL.Null,
    'nearby20' : IDL.Null,
    'camera' : IDL.Null,
    'gallery' : IDL.Null,
  });
  const NearbyPost = IDL.Record({
    'id' : IDL.Text,
    'originalId' : IDL.Text,
    'owner' : IDL.Principal,
    'metadata' : MediaMetadata,
    'location' : IDL.Text,
  });
  const EnhancedSidebarState = IDL.Record({
    'isOpen' : IDL.Bool,
    'activeWindow' : Window,
    'position' : IDL.Text,
  });
  const SideBarResponse = IDL.Variant({
    'error' : IDL.Text,
    'success' : EnhancedSidebarState,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCommentToMedia' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addFilterPreset' : IDL.Func(
        [
          IDL.Text,
          IDL.Record({
            'contrast' : IDL.Float64,
            'brightness' : IDL.Float64,
            'saturation' : IDL.Float64,
          }),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMedia' : IDL.Func([IDL.Text], [], []),
    'getAllEntertainmentPosts' : IDL.Func(
        [],
        [IDL.Vec(EntertainmentPost)],
        ['query'],
      ),
    'getAllEntertainmentPostsSorted' : IDL.Func(
        [],
        [IDL.Vec(EntertainmentPost)],
        ['query'],
      ),
    'getAllFilterPresets' : IDL.Func([], [IDL.Vec(FilterPreset)], ['query']),
    'getAllMediaMetadata' : IDL.Func([], [IDL.Vec(MediaMetadata)], ['query']),
    'getAllNonExpiredStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentWindow' : IDL.Func([], [Window], ['query']),
    'getEntertainmentPost' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(EntertainmentPost)],
        ['query'],
      ),
    'getMediaByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MediaMetadata)],
        ['query'],
      ),
    'getMediaByTag' : IDL.Func([IDL.Text], [IDL.Vec(MediaMetadata)], ['query']),
    'getMediaMetadata' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MediaMetadata)],
        ['query'],
      ),
    'getMostPopularMedia' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MediaMetadata)],
        ['query'],
      ),
    'getNearbyPosts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(NearbyPost)],
        ['query'],
      ),
    'getNearbyPostsWithinTimeRange' : IDL.Func(
        [IDL.Text, Time, Time],
        [IDL.Vec(NearbyPost)],
        ['query'],
      ),
    'getNonExpiredUserStories' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Story)],
        ['query'],
      ),
    'getPostsByAuthor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(EntertainmentPost)],
        ['query'],
      ),
    'getSidebarState' : IDL.Func([], [SideBarResponse], ['query']),
    'getStory' : IDL.Func([IDL.Text], [IDL.Opt(Story)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfilesByUsername' : IDL.Func(
        [],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getUserStories' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAREffect' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveEntertainmentPost' : IDL.Func([EntertainmentPost], [], []),
    'saveMedia' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          ExternalBlob,
          IDL.Principal,
          IDL.Bool,
          IDL.Opt(IDL.Nat),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'saveNearbyPost' : IDL.Func([NearbyPost], [], []),
    'saveUserStory' : IDL.Func([Story], [], []),
    'setFavoriteStatusForMedia' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setLikeStatusForMedia' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setSidebarPosition' : IDL.Func([IDL.Text], [], []),
    'switchWindow' : IDL.Func([Window], [], []),
    'toggleSidebar' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };