/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface EnhancedSidebarState {
  'isOpen' : boolean,
  'activeWindow' : Window,
  'position' : string,
}
export interface EntertainmentPost {
  'id' : string,
  'content' : string,
  'tags' : Array<string>,
  'author' : Principal,
  'likes' : bigint,
  'creationDate' : Time,
  'comments' : Array<Comment>,
  'mediaId' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export interface FilterPreset {
  'name' : string,
  'settings' : {
    'contrast' : number,
    'brightness' : number,
    'saturation' : number,
  },
}
export interface MediaMetadata {
  'id' : string,
  'duration' : [] | [bigint],
  'owner' : Principal,
  'blob' : ExternalBlob,
  'tags' : Array<string>,
  'ratings' : Ratings,
  'likedBy' : Array<Principal>,
  'isFavorite' : boolean,
  'likes' : bigint,
  'filename' : string,
  'creationDate' : Time,
  'comments' : Array<Comment>,
  'isVideo' : boolean,
  'arEffectsApplied' : Array<string>,
  'filtersApplied' : Array<string>,
}
export interface NearbyPost {
  'id' : string,
  'originalId' : string,
  'owner' : Principal,
  'metadata' : MediaMetadata,
  'location' : string,
}
export interface Ratings {
  'funFactor' : number,
  'creative' : number,
  'technical' : number,
  'overall' : number,
}
export type SideBarResponse = { 'error' : string } |
  { 'success' : EnhancedSidebarState };
export interface Story {
  'id' : string,
  'owner' : Principal,
  'tags' : Array<string>,
  'creationDate' : Time,
  'expirationDate' : Time,
  'viewers' : Array<Principal>,
  'mediaId' : string,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'stories' : Array<string>,
  'posts' : Array<string>,
  'profilePictureBlob' : [] | [ExternalBlob],
  'videos' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Window = { 'editing' : null } |
  { 'entertainment' : null } |
  { 'stories' : null } |
  { 'aiTools' : null } |
  { 'lucky' : null } |
  { 'enhance' : null } |
  { 'settings' : null } |
  { 'nearby20' : null } |
  { 'camera' : null } |
  { 'gallery' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCommentToMedia' : ActorMethod<[string, string], undefined>,
  'addFilterPreset' : ActorMethod<
    [
      string,
      { 'contrast' : number, 'brightness' : number, 'saturation' : number },
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMedia' : ActorMethod<[string], undefined>,
  'getAllEntertainmentPosts' : ActorMethod<[], Array<EntertainmentPost>>,
  'getAllEntertainmentPostsSorted' : ActorMethod<[], Array<EntertainmentPost>>,
  'getAllFilterPresets' : ActorMethod<[], Array<FilterPreset>>,
  'getAllMediaMetadata' : ActorMethod<[], Array<MediaMetadata>>,
  'getAllNonExpiredStories' : ActorMethod<[], Array<Story>>,
  'getAllStories' : ActorMethod<[], Array<Story>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentWindow' : ActorMethod<[], Window>,
  'getEntertainmentPost' : ActorMethod<[string], [] | [EntertainmentPost]>,
  'getMediaByOwner' : ActorMethod<[Principal], Array<MediaMetadata>>,
  'getMediaByTag' : ActorMethod<[string], Array<MediaMetadata>>,
  'getMediaMetadata' : ActorMethod<[string], [] | [MediaMetadata]>,
  'getMostPopularMedia' : ActorMethod<[bigint], Array<MediaMetadata>>,
  'getNearbyPosts' : ActorMethod<[Principal], Array<NearbyPost>>,
  'getNearbyPostsWithinTimeRange' : ActorMethod<
    [string, Time, Time],
    Array<NearbyPost>
  >,
  'getNonExpiredUserStories' : ActorMethod<[Principal], Array<Story>>,
  'getPostsByAuthor' : ActorMethod<[Principal], Array<EntertainmentPost>>,
  'getSidebarState' : ActorMethod<[], SideBarResponse>,
  'getStory' : ActorMethod<[string], [] | [Story]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfilesByUsername' : ActorMethod<[], Array<UserProfile>>,
  'getUserStories' : ActorMethod<[Principal], Array<Story>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveAREffect' : ActorMethod<[string, string, string, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveEntertainmentPost' : ActorMethod<[EntertainmentPost], undefined>,
  'saveMedia' : ActorMethod<
    [
      string,
      string,
      Array<string>,
      Array<string>,
      ExternalBlob,
      Principal,
      boolean,
      [] | [bigint],
      Array<string>,
    ],
    undefined
  >,
  'saveNearbyPost' : ActorMethod<[NearbyPost], undefined>,
  'saveUserStory' : ActorMethod<[Story], undefined>,
  'setFavoriteStatusForMedia' : ActorMethod<[string, boolean], undefined>,
  'setLikeStatusForMedia' : ActorMethod<[string, boolean], undefined>,
  'setSidebarPosition' : ActorMethod<[string], undefined>,
  'switchWindow' : ActorMethod<[Window], undefined>,
  'toggleSidebar' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];