/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export type SideBarResponse = {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: EnhancedSidebarState;
};
export interface Comment {
    content: string;
    author: Principal;
    timestamp: Time;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Story {
    id: string;
    owner: Principal;
    tags: Array<string>;
    creationDate: Time;
    expirationDate: Time;
    viewers: Array<Principal>;
    mediaId: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface FilterPreset {
    name: string;
    settings: {
        contrast: number;
        brightness: number;
        saturation: number;
    };
}
export interface EntertainmentPost {
    id: string;
    content: string;
    tags: Array<string>;
    author: Principal;
    likes: bigint;
    creationDate: Time;
    comments: Array<Comment>;
    mediaId?: string;
}
export interface EnhancedSidebarState {
    isOpen: boolean;
    activeWindow: Window;
    position: string;
}
export interface NearbyPost {
    id: string;
    originalId: string;
    owner: Principal;
    metadata: MediaMetadata;
    location: string;
}
export interface Ratings {
    funFactor: number;
    creative: number;
    technical: number;
    overall: number;
}
export interface MediaMetadata {
    id: string;
    duration?: bigint;
    owner: Principal;
    blob: ExternalBlob;
    tags: Array<string>;
    ratings: Ratings;
    likedBy: Array<Principal>;
    isFavorite: boolean;
    likes: bigint;
    filename: string;
    creationDate: Time;
    comments: Array<Comment>;
    isVideo: boolean;
    arEffectsApplied: Array<string>;
    filtersApplied: Array<string>;
}
export interface UserProfile {
    bio: string;
    username: string;
    stories: Array<string>;
    posts: Array<string>;
    profilePictureBlob?: ExternalBlob;
    videos: Array<string>;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Window {
    editing = "editing",
    entertainment = "entertainment",
    stories = "stories",
    aiTools = "aiTools",
    lucky = "lucky",
    enhance = "enhance",
    settings = "settings",
    nearby20 = "nearby20",
    camera = "camera",
    gallery = "gallery"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCommentToMedia(mediaId: string, comment: string): Promise<void>;
    addFilterPreset(name: string, settings: {
        contrast: number;
        brightness: number;
        saturation: number;
    }): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteMedia(id: string): Promise<void>;
    getAllEntertainmentPosts(): Promise<Array<EntertainmentPost>>;
    getAllEntertainmentPostsSorted(): Promise<Array<EntertainmentPost>>;
    getAllFilterPresets(): Promise<Array<FilterPreset>>;
    getAllMediaMetadata(): Promise<Array<MediaMetadata>>;
    getAllNonExpiredStories(): Promise<Array<Story>>;
    getAllStories(): Promise<Array<Story>>;
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentWindow(): Promise<Window>;
    getEntertainmentPost(postId: string): Promise<EntertainmentPost | null>;
    getMediaByOwner(owner: Principal): Promise<Array<MediaMetadata>>;
    getMediaByTag(tag: string): Promise<Array<MediaMetadata>>;
    getMediaMetadata(id: string): Promise<MediaMetadata | null>;
    getMostPopularMedia(limit: bigint): Promise<Array<MediaMetadata>>;
    getNearbyPosts(owner: Principal): Promise<Array<NearbyPost>>;
    getNearbyPostsWithinTimeRange(location: string, startTime: Time, endTime: Time): Promise<Array<NearbyPost>>;
    getNonExpiredUserStories(owner: Principal): Promise<Array<Story>>;
    getPostsByAuthor(author: Principal): Promise<Array<EntertainmentPost>>;
    getSidebarState(): Promise<SideBarResponse>;
    getStory(storyId: string): Promise<Story | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserProfilesByUsername(): Promise<Array<UserProfile>>;
    getUserStories(owner: Principal): Promise<Array<Story>>;
    isCallerAdmin(): Promise<boolean>;
    saveAREffect(name: string, description: string, assetReference: string, isAnimated: boolean): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveEntertainmentPost(post: EntertainmentPost): Promise<void>;
    saveMedia(id: string, filename: string, filters: Array<string>, arEffects: Array<string>, blob: ExternalBlob, owner: Principal, isVideo: boolean, duration: bigint | null, tags: Array<string>): Promise<void>;
    saveNearbyPost(post: NearbyPost): Promise<void>;
    saveUserStory(story: Story): Promise<void>;
    setFavoriteStatusForMedia(mediaId: string, isFavorite: boolean): Promise<void>;
    setLikeStatusForMedia(mediaId: string, isLiked: boolean): Promise<void>;
    setSidebarPosition(position: string): Promise<void>;
    switchWindow(window: Window): Promise<void>;
    toggleSidebar(): Promise<void>;
}
import type { Comment as _Comment, EnhancedSidebarState as _EnhancedSidebarState, EntertainmentPost as _EntertainmentPost, ExternalBlob as _ExternalBlob, MediaMetadata as _MediaMetadata, NearbyPost as _NearbyPost, Ratings as _Ratings, SideBarResponse as _SideBarResponse, Story as _Story, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, Window as _Window, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCommentToMedia(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCommentToMedia(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCommentToMedia(arg0, arg1);
            return result;
        }
    }
    async addFilterPreset(arg0: string, arg1: {
        contrast: number;
        brightness: number;
        saturation: number;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFilterPreset(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFilterPreset(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteMedia(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedia(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedia(arg0);
            return result;
        }
    }
    async getAllEntertainmentPosts(): Promise<Array<EntertainmentPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEntertainmentPosts();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEntertainmentPosts();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEntertainmentPostsSorted(): Promise<Array<EntertainmentPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEntertainmentPostsSorted();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEntertainmentPostsSorted();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFilterPresets(): Promise<Array<FilterPreset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFilterPresets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFilterPresets();
            return result;
        }
    }
    async getAllMediaMetadata(): Promise<Array<MediaMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMediaMetadata();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMediaMetadata();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNonExpiredStories(): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNonExpiredStories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNonExpiredStories();
            return result;
        }
    }
    async getAllStories(): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStories();
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentWindow(): Promise<Window> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentWindow();
                return from_candid_Window_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentWindow();
            return from_candid_Window_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntertainmentPost(arg0: string): Promise<EntertainmentPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntertainmentPost(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntertainmentPost(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMediaByOwner(arg0: Principal): Promise<Array<MediaMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaByOwner(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaByOwner(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMediaByTag(arg0: string): Promise<Array<MediaMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaByTag(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaByTag(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMediaMetadata(arg0: string): Promise<MediaMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaMetadata(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaMetadata(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMostPopularMedia(arg0: bigint): Promise<Array<MediaMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMostPopularMedia(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMostPopularMedia(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNearbyPosts(arg0: Principal): Promise<Array<NearbyPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNearbyPosts(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNearbyPosts(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNearbyPostsWithinTimeRange(arg0: string, arg1: Time, arg2: Time): Promise<Array<NearbyPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNearbyPostsWithinTimeRange(arg0, arg1, arg2);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNearbyPostsWithinTimeRange(arg0, arg1, arg2);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNonExpiredUserStories(arg0: Principal): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNonExpiredUserStories(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNonExpiredUserStories(arg0);
            return result;
        }
    }
    async getPostsByAuthor(arg0: Principal): Promise<Array<EntertainmentPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsByAuthor(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsByAuthor(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSidebarState(): Promise<SideBarResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getSidebarState();
                return from_candid_SideBarResponse_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSidebarState();
            return from_candid_SideBarResponse_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStory(arg0: string): Promise<Story | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStory(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStory(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfilesByUsername(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfilesByUsername();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfilesByUsername();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserStories(arg0: Principal): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStories(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStories(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveAREffect(arg0: string, arg1: string, arg2: string, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAREffect(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAREffect(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveEntertainmentPost(arg0: EntertainmentPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEntertainmentPost(to_candid_EntertainmentPost_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEntertainmentPost(to_candid_EntertainmentPost_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveMedia(arg0: string, arg1: string, arg2: Array<string>, arg3: Array<string>, arg4: ExternalBlob, arg5: Principal, arg6: boolean, arg7: bigint | null, arg8: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMedia(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n39(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg7), arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMedia(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n39(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg7), arg8);
            return result;
        }
    }
    async saveNearbyPost(arg0: NearbyPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveNearbyPost(await to_candid_NearbyPost_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveNearbyPost(await to_candid_NearbyPost_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveUserStory(arg0: Story): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserStory(arg0);
            return result;
        }
    }
    async setFavoriteStatusForMedia(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFavoriteStatusForMedia(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFavoriteStatusForMedia(arg0, arg1);
            return result;
        }
    }
    async setLikeStatusForMedia(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLikeStatusForMedia(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLikeStatusForMedia(arg0, arg1);
            return result;
        }
    }
    async setSidebarPosition(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSidebarPosition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSidebarPosition(arg0);
            return result;
        }
    }
    async switchWindow(arg0: Window): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.switchWindow(to_candid_Window_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.switchWindow(to_candid_Window_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async toggleSidebar(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleSidebar();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleSidebar();
            return result;
        }
    }
}
function from_candid_EnhancedSidebarState_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnhancedSidebarState): EnhancedSidebarState {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_EntertainmentPost_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EntertainmentPost): EntertainmentPost {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_MediaMetadata_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaMetadata): Promise<MediaMetadata> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function from_candid_NearbyPost_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NearbyPost): Promise<NearbyPost> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_SideBarResponse_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SideBarResponse): SideBarResponse {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Window_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Window): Window {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EntertainmentPost]): EntertainmentPost | null {
    return value.length === 0 ? null : from_candid_EntertainmentPost_n11(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MediaMetadata]): Promise<MediaMetadata | null> {
    return value.length === 0 ? null : await from_candid_MediaMetadata_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Story]): Story | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    tags: Array<string>;
    author: Principal;
    likes: bigint;
    creationDate: _Time;
    comments: Array<_Comment>;
    mediaId: [] | [string];
}): {
    id: string;
    content: string;
    tags: Array<string>;
    author: Principal;
    likes: bigint;
    creationDate: Time;
    comments: Array<Comment>;
    mediaId?: string;
} {
    return {
        id: value.id,
        content: value.content,
        tags: value.tags,
        author: value.author,
        likes: value.likes,
        creationDate: value.creationDate,
        comments: value.comments,
        mediaId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.mediaId))
    };
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    duration: [] | [bigint];
    owner: Principal;
    blob: _ExternalBlob;
    tags: Array<string>;
    ratings: _Ratings;
    likedBy: Array<Principal>;
    isFavorite: boolean;
    likes: bigint;
    filename: string;
    creationDate: _Time;
    comments: Array<_Comment>;
    isVideo: boolean;
    arEffectsApplied: Array<string>;
    filtersApplied: Array<string>;
}): Promise<{
    id: string;
    duration?: bigint;
    owner: Principal;
    blob: ExternalBlob;
    tags: Array<string>;
    ratings: Ratings;
    likedBy: Array<Principal>;
    isFavorite: boolean;
    likes: bigint;
    filename: string;
    creationDate: Time;
    comments: Array<Comment>;
    isVideo: boolean;
    arEffectsApplied: Array<string>;
    filtersApplied: Array<string>;
}> {
    return {
        id: value.id,
        duration: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.duration)),
        owner: value.owner,
        blob: await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.blob),
        tags: value.tags,
        ratings: value.ratings,
        likedBy: value.likedBy,
        isFavorite: value.isFavorite,
        likes: value.likes,
        filename: value.filename,
        creationDate: value.creationDate,
        comments: value.comments,
        isVideo: value.isVideo,
        arEffectsApplied: value.arEffectsApplied,
        filtersApplied: value.filtersApplied
    };
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    stories: Array<string>;
    posts: Array<string>;
    profilePictureBlob: [] | [_ExternalBlob];
    videos: Array<string>;
}): Promise<{
    bio: string;
    username: string;
    stories: Array<string>;
    posts: Array<string>;
    profilePictureBlob?: ExternalBlob;
    videos: Array<string>;
}> {
    return {
        bio: value.bio,
        username: value.username,
        stories: value.stories,
        posts: value.posts,
        profilePictureBlob: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.profilePictureBlob)),
        videos: value.videos
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    originalId: string;
    owner: Principal;
    metadata: _MediaMetadata;
    location: string;
}): Promise<{
    id: string;
    originalId: string;
    owner: Principal;
    metadata: MediaMetadata;
    location: string;
}> {
    return {
        id: value.id,
        originalId: value.originalId,
        owner: value.owner,
        metadata: await from_candid_MediaMetadata_n15(_uploadFile, _downloadFile, value.metadata),
        location: value.location
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isOpen: boolean;
    activeWindow: _Window;
    position: string;
}): {
    isOpen: boolean;
    activeWindow: Window;
    position: string;
} {
    return {
        isOpen: value.isOpen,
        activeWindow: from_candid_Window_n25(_uploadFile, _downloadFile, value.activeWindow),
        position: value.position
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    editing: null;
} | {
    entertainment: null;
} | {
    stories: null;
} | {
    aiTools: null;
} | {
    lucky: null;
} | {
    enhance: null;
} | {
    settings: null;
} | {
    nearby20: null;
} | {
    camera: null;
} | {
    gallery: null;
}): Window {
    return "editing" in value ? Window.editing : "entertainment" in value ? Window.entertainment : "stories" in value ? Window.stories : "aiTools" in value ? Window.aiTools : "lucky" in value ? Window.lucky : "enhance" in value ? Window.enhance : "settings" in value ? Window.settings : "nearby20" in value ? Window.nearby20 : "camera" in value ? Window.camera : "gallery" in value ? Window.gallery : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: string;
} | {
    success: _EnhancedSidebarState;
}): {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: EnhancedSidebarState;
} {
    return "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "success" in value ? {
        __kind__: "success",
        success: from_candid_EnhancedSidebarState_n34(_uploadFile, _downloadFile, value.success)
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EntertainmentPost>): Array<EntertainmentPost> {
    return value.map((x)=>from_candid_EntertainmentPost_n11(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MediaMetadata>): Promise<Array<MediaMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MediaMetadata_n15(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Promise<Array<UserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfile_n19(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NearbyPost>): Promise<Array<NearbyPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_NearbyPost_n30(_uploadFile, _downloadFile, x)));
}
function to_candid_EntertainmentPost_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntertainmentPost): _EntertainmentPost {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_MediaMetadata_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaMetadata): Promise<_MediaMetadata> {
    return await to_candid_record_n46(_uploadFile, _downloadFile, value);
}
async function to_candid_NearbyPost_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NearbyPost): Promise<_NearbyPost> {
    return await to_candid_record_n44(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Window_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Window): _Window {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    stories: Array<string>;
    posts: Array<string>;
    profilePictureBlob?: ExternalBlob;
    videos: Array<string>;
}): Promise<{
    bio: string;
    username: string;
    stories: Array<string>;
    posts: Array<string>;
    profilePictureBlob: [] | [_ExternalBlob];
    videos: Array<string>;
}> {
    return {
        bio: value.bio,
        username: value.username,
        stories: value.stories,
        posts: value.posts,
        profilePictureBlob: value.profilePictureBlob ? candid_some(await to_candid_ExternalBlob_n39(_uploadFile, _downloadFile, value.profilePictureBlob)) : candid_none(),
        videos: value.videos
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    tags: Array<string>;
    author: Principal;
    likes: bigint;
    creationDate: Time;
    comments: Array<Comment>;
    mediaId?: string;
}): {
    id: string;
    content: string;
    tags: Array<string>;
    author: Principal;
    likes: bigint;
    creationDate: _Time;
    comments: Array<_Comment>;
    mediaId: [] | [string];
} {
    return {
        id: value.id,
        content: value.content,
        tags: value.tags,
        author: value.author,
        likes: value.likes,
        creationDate: value.creationDate,
        comments: value.comments,
        mediaId: value.mediaId ? candid_some(value.mediaId) : candid_none()
    };
}
async function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    originalId: string;
    owner: Principal;
    metadata: MediaMetadata;
    location: string;
}): Promise<{
    id: string;
    originalId: string;
    owner: Principal;
    metadata: _MediaMetadata;
    location: string;
}> {
    return {
        id: value.id,
        originalId: value.originalId,
        owner: value.owner,
        metadata: await to_candid_MediaMetadata_n45(_uploadFile, _downloadFile, value.metadata),
        location: value.location
    };
}
async function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    duration?: bigint;
    owner: Principal;
    blob: ExternalBlob;
    tags: Array<string>;
    ratings: Ratings;
    likedBy: Array<Principal>;
    isFavorite: boolean;
    likes: bigint;
    filename: string;
    creationDate: Time;
    comments: Array<Comment>;
    isVideo: boolean;
    arEffectsApplied: Array<string>;
    filtersApplied: Array<string>;
}): Promise<{
    id: string;
    duration: [] | [bigint];
    owner: Principal;
    blob: _ExternalBlob;
    tags: Array<string>;
    ratings: _Ratings;
    likedBy: Array<Principal>;
    isFavorite: boolean;
    likes: bigint;
    filename: string;
    creationDate: _Time;
    comments: Array<_Comment>;
    isVideo: boolean;
    arEffectsApplied: Array<string>;
    filtersApplied: Array<string>;
}> {
    return {
        id: value.id,
        duration: value.duration ? candid_some(value.duration) : candid_none(),
        owner: value.owner,
        blob: await to_candid_ExternalBlob_n39(_uploadFile, _downloadFile, value.blob),
        tags: value.tags,
        ratings: value.ratings,
        likedBy: value.likedBy,
        isFavorite: value.isFavorite,
        likes: value.likes,
        filename: value.filename,
        creationDate: value.creationDate,
        comments: value.comments,
        isVideo: value.isVideo,
        arEffectsApplied: value.arEffectsApplied,
        filtersApplied: value.filtersApplied
    };
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Window): {
    editing: null;
} | {
    entertainment: null;
} | {
    stories: null;
} | {
    aiTools: null;
} | {
    lucky: null;
} | {
    enhance: null;
} | {
    settings: null;
} | {
    nearby20: null;
} | {
    camera: null;
} | {
    gallery: null;
} {
    return value == Window.editing ? {
        editing: null
    } : value == Window.entertainment ? {
        entertainment: null
    } : value == Window.stories ? {
        stories: null
    } : value == Window.aiTools ? {
        aiTools: null
    } : value == Window.lucky ? {
        lucky: null
    } : value == Window.enhance ? {
        enhance: null
    } : value == Window.settings ? {
        settings: null
    } : value == Window.nearby20 ? {
        nearby20: null
    } : value == Window.camera ? {
        camera: null
    } : value == Window.gallery ? {
        gallery: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
